import Providers from "@/utils/provider";
import React from "react";
import 'react-loading-skeleton/dist/skeleton.css'


export const metadata = {
    title: "Schools",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <>{children}</>
    );
}
