import React from "react";
export const metadata = {
    title: "Exams",
    description: "Generated by create next app",
};

export const ExamLayout = ({ children, }: { children: React.ReactNode }) => {
    return <>{children}</>;
}

export default ExamLayout;
