import { SchoolFilterProvider } from "@/components/School/FilterContext";
import React from "react";


export const metadata = {
    title: "Schools",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <SchoolFilterProvider>{children}</SchoolFilterProvider>
    );
}
